const MONITOR_SCENARIO_CATALOG = Object.freeze({
  stable_sinus: {
    key: "stable_sinus",
    label: "稳定窦律监护",
    description: "模拟常规床旁监护，包含 ECG、RESP、PLETH 与有创动脉压。",
    monitorLabel: "通用监护仪",
    channels: [
      {
        code: "ECG",
        label: "ECG II",
        color: "#32d583",
        unit: "mV",
        samplingRate: 250,
        lowerLimit: -1.8,
        upperLimit: 2.2,
        kind: "ecg",
      },
      {
        code: "RESP",
        label: "呼吸波",
        color: "#36bffa",
        unit: "a.u.",
        samplingRate: 62,
        lowerLimit: -1.4,
        upperLimit: 1.4,
        kind: "resp",
      },
      {
        code: "PLETH",
        label: "脉搏容积波",
        color: "#fdb022",
        unit: "a.u.",
        samplingRate: 125,
        lowerLimit: -0.2,
        upperLimit: 1.8,
        kind: "pleth",
      },
      {
        code: "ART",
        label: "有创动脉压",
        color: "#fb7185",
        unit: "mmHg",
        samplingRate: 125,
        lowerLimit: 20,
        upperLimit: 160,
        kind: "art",
      },
    ],
    signal: {
      heartRate: 74,
      arrhythmia: 0.02,
      respRate: 16,
      meanPressure: 88,
      pulsePressure: 38,
      plethAmplitude: 1.05,
      co2Level: 36,
    },
  },
  afib_fast: {
    key: "afib_fast",
    label: "快速房颤监护",
    description: "强调心率不齐与脉搏振幅波动，适合验证实时波形滚动与自适应量程。",
    monitorLabel: "心电监护仪",
    channels: [
      {
        code: "ECG",
        label: "ECG V1",
        color: "#32d583",
        unit: "mV",
        samplingRate: 250,
        lowerLimit: -2.2,
        upperLimit: 2.4,
        kind: "ecg",
      },
      {
        code: "RESP",
        label: "呼吸阻抗",
        color: "#36bffa",
        unit: "a.u.",
        samplingRate: 62,
        lowerLimit: -1.5,
        upperLimit: 1.5,
        kind: "resp",
      },
      {
        code: "PLETH",
        label: "SpO2 容积波",
        color: "#fdb022",
        unit: "a.u.",
        samplingRate: 125,
        lowerLimit: -0.2,
        upperLimit: 1.8,
        kind: "pleth",
      },
      {
        code: "CO2",
        label: "呼末二氧化碳",
        color: "#a855f7",
        unit: "mmHg",
        samplingRate: 62,
        lowerLimit: -2,
        upperLimit: 55,
        kind: "co2",
      },
    ],
    signal: {
      heartRate: 136,
      arrhythmia: 0.18,
      respRate: 24,
      meanPressure: 82,
      pulsePressure: 22,
      plethAmplitude: 0.72,
      co2Level: 31,
    },
  },
  invasive_support: {
    key: "invasive_support",
    label: "循环支持监护",
    description: "加入 CVP 与动脉压力变化，用于 ICU 侵入式监护波形演示。",
    monitorLabel: "ICU 监护终端",
    channels: [
      {
        code: "ECG",
        label: "ECG II",
        color: "#32d583",
        unit: "mV",
        samplingRate: 250,
        lowerLimit: -2,
        upperLimit: 2.4,
        kind: "ecg",
      },
      {
        code: "RESP",
        label: "呼吸波",
        color: "#36bffa",
        unit: "a.u.",
        samplingRate: 62,
        lowerLimit: -1.3,
        upperLimit: 1.3,
        kind: "resp",
      },
      {
        code: "ART",
        label: "有创动脉压",
        color: "#fb7185",
        unit: "mmHg",
        samplingRate: 125,
        lowerLimit: 15,
        upperLimit: 170,
        kind: "art",
      },
      {
        code: "CVP",
        label: "中心静脉压",
        color: "#2dd4bf",
        unit: "mmHg",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 22,
        kind: "cvp",
      },
    ],
    signal: {
      heartRate: 96,
      arrhythmia: 0.05,
      respRate: 20,
      meanPressure: 72,
      pulsePressure: 26,
      plethAmplitude: 0.86,
      co2Level: 34,
      cvpBaseline: 10,
    },
  },
});

const VENTILATOR_SCENARIO_CATALOG = Object.freeze({
  ac_volume: {
    key: "ac_volume",
    label: "容量控制通气",
    description: "典型的 VCV 波形，带压力、流速、容量三联波形与环图。",
    ventilatorLabel: "呼吸机",
    waveforms: [
      {
        code: "PAW",
        label: "气道压力",
        color: "#4f7cff",
        unit: "cmH2O",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 35,
      },
      {
        code: "FLOW",
        label: "流速",
        color: "#22c55e",
        unit: "L/min",
        samplingRate: 80,
        lowerLimit: -55,
        upperLimit: 60,
      },
      {
        code: "VOLUME",
        label: "容量",
        color: "#f97316",
        unit: "mL",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 650,
      },
    ],
    loops: [
      { key: "Paw-V", label: "压力-容量环", xUnit: "mL", yUnit: "cmH2O", color: "#4f7cff" },
      { key: "Flow-Paw", label: "流速-压力环", xUnit: "L/min", yUnit: "cmH2O", color: "#22c55e" },
      { key: "V-Flow", label: "容量-流速环", xUnit: "mL", yUnit: "L/min", color: "#f97316" },
    ],
    signal: {
      rate: 14,
      tidalVolume: 480,
      peep: 6,
      pip: 24,
      plateau: 19,
      inspiratoryRatio: 0.34,
      inspiratoryFlow: 48,
      expiratoryFlow: -34,
    },
  },
  pressure_control: {
    key: "pressure_control",
    label: "压力控制通气",
    description: "强调压力平台与减速流速波形，适合验证呼吸机工作区布局。",
    ventilatorLabel: "呼吸机",
    waveforms: [
      {
        code: "PAW",
        label: "气道压力",
        color: "#4f7cff",
        unit: "cmH2O",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 40,
      },
      {
        code: "FLOW",
        label: "流速",
        color: "#22c55e",
        unit: "L/min",
        samplingRate: 80,
        lowerLimit: -60,
        upperLimit: 65,
      },
      {
        code: "VOLUME",
        label: "容量",
        color: "#f97316",
        unit: "mL",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 720,
      },
    ],
    loops: [
      { key: "Paw-V", label: "压力-容量环", xUnit: "mL", yUnit: "cmH2O", color: "#4f7cff" },
      { key: "Flow-Paw", label: "流速-压力环", xUnit: "L/min", yUnit: "cmH2O", color: "#22c55e" },
      { key: "V-Flow", label: "容量-流速环", xUnit: "mL", yUnit: "L/min", color: "#f97316" },
    ],
    signal: {
      rate: 18,
      tidalVolume: 430,
      peep: 8,
      pip: 30,
      plateau: 26,
      inspiratoryRatio: 0.4,
      inspiratoryFlow: 56,
      expiratoryFlow: -42,
    },
  },
  weaning_trial: {
    key: "weaning_trial",
    label: "撤机评估",
    description: "模拟自主呼吸增强阶段，便于观察流速与环图变化。",
    ventilatorLabel: "呼吸机",
    waveforms: [
      {
        code: "PAW",
        label: "气道压力",
        color: "#4f7cff",
        unit: "cmH2O",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 28,
      },
      {
        code: "FLOW",
        label: "流速",
        color: "#22c55e",
        unit: "L/min",
        samplingRate: 80,
        lowerLimit: -50,
        upperLimit: 52,
      },
      {
        code: "VOLUME",
        label: "容量",
        color: "#f97316",
        unit: "mL",
        samplingRate: 80,
        lowerLimit: 0,
        upperLimit: 520,
      },
    ],
    loops: [
      { key: "Paw-V", label: "压力-容量环", xUnit: "mL", yUnit: "cmH2O", color: "#4f7cff" },
      { key: "Flow-Paw", label: "流速-压力环", xUnit: "L/min", yUnit: "cmH2O", color: "#22c55e" },
      { key: "V-Flow", label: "容量-流速环", xUnit: "mL", yUnit: "L/min", color: "#f97316" },
    ],
    signal: {
      rate: 22,
      tidalVolume: 360,
      peep: 5,
      pip: 18,
      plateau: 15,
      inspiratoryRatio: 0.32,
      inspiratoryFlow: 36,
      expiratoryFlow: -28,
    },
  },
});

export const monitorScenarioCatalog = MONITOR_SCENARIO_CATALOG;
export const ventilatorScenarioCatalog = VENTILATOR_SCENARIO_CATALOG;

export const monitorScenarioOptions = Object.freeze(
  Object.values(MONITOR_SCENARIO_CATALOG).map((item) => ({
    value: item.key,
    label: item.label,
    description: item.description,
  })),
);

export const ventilatorScenarioOptions = Object.freeze(
  Object.values(VENTILATOR_SCENARIO_CATALOG).map((item) => ({
    value: item.key,
    label: item.label,
    description: item.description,
  })),
);

export function getMonitorScenarioConfig(key = "stable_sinus") {
  return MONITOR_SCENARIO_CATALOG[key] || MONITOR_SCENARIO_CATALOG.stable_sinus;
}

export function getVentilatorScenarioConfig(key = "ac_volume") {
  return (
    VENTILATOR_SCENARIO_CATALOG[key] || VENTILATOR_SCENARIO_CATALOG.ac_volume
  );
}
